Pin mysql-connector-python to 8.4.0
9.0.0 causes the following error with mariadb:
```raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2059 (HY000): Authentication plugin
'mysql_native_password' cannot be loaded: /usr/lib/mysql/plugin/mysql_native_password.so:
cannot open shared object file: No such file or directory```